### ISSUE TITLE
When using a personal access token with github, receive 422 error

### ISSUE THREAD

**Issue by jasongonzales23** [dtschust/redux-bug-reporter#27] opened 2017-06-15 00:08 UTC
```
{
  "message": "Validation Failed",
  "errors": [
    {
      "resource": "Issue",
      "code": "custom",
      "field": "body",
      "message": "body is too long (maximum is 65536 characters)"
    }
  ],
  "documentation_url": "https://developer.github.com/v3/issues/#create-an-issue"
}
```
Not sure if this is even fixable, so if not, perhaps mention in the docs?

**Comment by dtschust** [comment] 2017-06-15 00:34
Yeah, it looks like this is a github API limitation. Do you think this might be a result of your redux state being quite large, or perhaps a lot of actions happening on the page? If the redux state is large perhaps you could use the [redaction hooks](https://github.com/dtschust/redux-bug-reporter#redacting-sensitive-data) to make it smaller, although you could break bug playback. If you have a lot of actions that are causing the payload to be large then I'd say this is a dupe of #24

**Comment by jasongonzales23** [comment] 2017-06-15 01:46
Yep, sounds like it's large state. I will just try using Sheetsu. Not to change the subject, but it looks like the use of Sheetsu requires a proxy?

**Comment by dtschust** [comment] 2017-06-15 16:05
You shouldn't need a proxy for Sheetsu, does [the pattern in the docs](https://github.com/dtschust/redux-bug-reporter/blob/master/docs/integrations.md#sheetsu) throw an error? I updated the formatting in the docs, looks like github changed how they handle markdown since I wrote it.

**Comment by jasongonzales23** [comment] 2017-06-15 16:10
I think again it's an issue of the POST body being bigger than they want to handle. Perhaps on a paid plan the body can be bigger? I will mess with it a bit, that said, I think you can close this issue and thanks for the responses!

**Closed** 2017-06-15 16:11 UTC
